"""ready to run pytest

Revision ID: 9769b4978528
Revises: 72637966fb42
Create Date: 2023-07-28 18:56:16.402482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9769b4978528'
down_revision = '72637966fb42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
